### ISSUE TITLE
Not clear if  TIMESCALEDB_TELEMETRY=off works

### ISSUE THREAD

**Issue by ztolley** [timescale/timescaledb-docker#147]
I start Timescale DB using a docker compose file, in environment variable that service I have:

```
services:
  timecale:
    image: timescale/timescaledb-postgis:2.3.0-pg13
    container_name: timescale
    restart: unless-stopped
    environment:
      - TIMESCALEDB_TELEMETRY=off
    env_file:
      - docker.env
    ports:
      - 5432:5432
 ```

The service starts up but in the console out for that container I still see 

```
timescale   | Note: TimescaleDB collects anonymous reports to better understand and assist our users.
timescale   | For more information and how to disable, please see our docs https://docs.timescaledb.com/using-timescaledb/telemetry.
```

I would expect it to show something like:

```
Note: Please enable telemetry to help us improve our product by running:...
```

so I'm not sure if it's just a bug showing the correct message or if the setting doesn't work and telemetry data is being sent.
