### ISSUE TITLE
timescaledb:2.8.1-pg14 The data is not stored at `/home/postgres/pgdata/data`

### ISSUE THREAD

**Issue by lionants02** [timescale/timescaledb-docker#196]
I lost my data.  Fortunately, there is no key information.
timescale/timescaledb:2.8.1-pg14
The data is not stored at `/home/postgres/pgdata/data`
But data is kept at `/var/lib/postgresql/data`

Might have to check again. But it's definitely not at `/home/postgres/pgdata/data`

My compose

```yaml
version: "3.4"

services:
  homeward_timescale:
    image: "timescale/timescaledb:2.8.1-pg14"
    restart: always
    ports:
      - 10335:5432 
    volumes:
            - "/data/a_med_care/timescale:/home/postgres/pgdata/data:rw"
    environment:
      POSTGRES_PASSWORD: YYCRuAcib7M67QVjDgRcGqxNVn9UsK
      TS_TUNE_MEMORY: 2GB
      TS_TUNE_NUM_CPUS: 4
      TS_TUNE_MAX_CONNS: 150
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 2100M
```

Good luck.
