### ISSUE TITLE
Timescale Docker Issue PG14

### ISSUE THREAD

**Issue by shaharzoo93** [timescale/timescaledb-docker#222]
Docker File - 
```
FROM timescale/timescaledb-ha:pg14

USER root
```
Docker Compose -
```
hot_raw_db:
    build:
      context: ./core_framework/db/hot_raw_db
      dockerfile: Dockerfile
    container_name: hot_raw_db
    stop_grace_period: 1m
    environment:
      - POSTGRES_DB=hot_raw_db
      - POSTGRES_USER=hot_raw_db
      - POSTGRES_PASSWORD=hot_raw_db
      - PGDATA=/var/lib/postgresql/data/pgdata
    command: postgres -c 'max_connections=1000'
    ports:
      - '7001:5432'
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'hot_raw_db']
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - './opt/volume/data/db/postgresql/hot_raw_db:/var/lib/postgresql/data'
    restart: always
    networks:
      - analytics_core_network
```
We used the above docker configuration for the container but we are facing the below error continuously 

 
![image](https://github.com/timescale/timescaledb-docker/assets/98393862/c4c2f6c2-547e-4f10-b691-3aba3f8a20bd)
