### ISSUE TITLE
data loss when upgrading timescale version

### ISSUE THREAD

**Issue by ecthiender** [timescale/timescaledb-docker#281]
## What
When updating the image tag of an existing running docker-compose service, and then running `docker compose up`, the new image wipes all existing data.

## Expected behaviour
New version of timescale image retains older data. If data directory is not compatible with new version, then it should report a FATAL error, instead of wiping out existing data.

## Steps to reproduce

1. Simple docker compose file for a timescaledb service

```yaml
services:
  timescaledb:
    image: timescale/timescaledb-ha:pg16.4-ts2.17.1
    ports:
      - 7432:5432
    environment:
      POSTGRES_PASSWORD: "password"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
```

Start the service - `docker compose up -d`

2. Connect via `psql`, and create a hypertable and insert data
```
CREATE TABLE measurements (
  timestamp TIMESTAMPTZ NOT NULL,
  temperature DOUBLE PRECISION
);

SELECT create_hypertable('measurements', by_range('timestamp'));

INSERT INTO measurements (timestamp, temperature) VALUES (now(), 22.3), (now(), 18.2), (now(), 25.2);
```

3. Check data is inserted and can be queried.

4. Update timescale version in docker compose

```
    image: timescale/timescaledb-ha:pg16.6-ts2.17.2
```

5. Run `docker compose up -d`

6. Connect via `psql` again and run `\dt`. There no tables anymore.
