### ISSUE TITLE
booting -pg14 yields libssl error

### ISSUE THREAD

**Issue by cdaringe** [timescale/timescaledb-docker#285]
# Problem

`Error loading shared library libssl.so.1.1: No such file or directory (needed by /usr/local/lib/postgresql/timescaledb-2.8.1.so)`

```yaml
# repro, compose file
services:
  db:
    image: timescale/timescaledb:latest-pg14
    restart: unless-stopped
    ports:
      - 5544:5544
    command: -p 5544
    environment:
      POSTGRES_USER: airman
      POSTGRES_PASSWORD: bigbadpassword # ;)
      POSTGRES_DB: pca
      TS_TUNE_MAX_BG_WORKERS: 8
```
