### ISSUE TITLE
`timescaledb:latest-pg9.6` complaining "sorry, too many clients already"

### ISSUE THREAD

**Issue by brettlyman** [timescale/timescaledb-docker#49]
We've been using `timescaledb/timescaledb:latest-pg9.6` for a while without problem, but this morning with the update to timescaledb 1.2.0 we started seeing the following error in our builds:

```
17:00:30.681 [error] Postgrex.Protocol (#PID<0.464.0>) failed to connect: ** (Postgrex.Error) FATAL 53300 (too_many_connections): sorry, too many clients already
17:00:30.883 [info] Failed to start Postgrex.Notifications due to: %Postgrex.Error{connection_id: nil, message: nil, postgres: %{code: :too_many_connections, file: "proc.c", line: "340", message: "sorry, too many clients already", pg_code: "53300", routine: "InitProcess", severity: "FATAL", unknown: "FATAL"}}
```

Setting our docker image to `timescaledb/timescaledb:1.1.1-pg9.6` makes it function properly. Perhaps an issue in the 1.2.0 update to timescaledb? Methinks that if there is an issue, that the `latest-pg9.6` tag should not point to the new version yet until that issue is resolved.

**Comment by RobAtticus** [comment]
Were you adjusting any settings in the config file, like `max_connections`? Do you have an idea of how many connections are usually active to your database?

**Comment by RobAtticus** [comment]
@brettlyman , the latest Docker images now ship with `timescaledb-tune` 0.4.0 which has improved suggestions for `max_connections`. Can you give it a try?

**Comment by noelzubin** [comment]
@brettlyman did you find any solution to this problem ?

**Comment by arjun289** [comment]
@RobAtticus is there a way to set the `max_connections` through env variables?

**Comment by jtushman** [comment]
similarly -- when I upgrade to 2.0 (timescale/timescaledb:2.0.0-pg12). I am not seeing the same error: "sorry, too many clients already". @RobAtticus what is the steps to rectify?

**Comment by jtushman** [comment]
if i tweak my compose like so ...
```
  timescaledb_test:
    image: 'timescale/timescaledb:2.0.0-pg12'
    container_name: 'timescaledb_test'
    ports:
      - '32769:5432'
    environment:
      POSTGRES_PASSWORD: '<password>'
      POSTGRES_USER: '<user>'
    command: ["-c", "max_connections=100"]
```

that fixes it (for me)
