### ISSUE TITLE
Problems in deploying timescaledb with updated official postgres helm chart based on bitnami

### ISSUE THREAD

**Issue by cloud-rocket** [timescale/timescaledb-docker#50]
I am trying to deploy timescaledb docker image `1.2.0-pg10-bitnami` with official postgres helm chart as the following:

```
helm install --name "myname" -f my-timescaledb-values.yaml stable/postgresql --set postgresqlPassword=<pass>
```
My values file is:
```
image:
  repository: timescale/timescaledb
#  tag: 1.2.0-pg10
  tag: 1.2.0-pg10-bitnami
metrics:
  enabled: true

persistence:
  enabled: true
  storageClass: ssd
  size: 200Gi

## PostgreSQL service configuration
service:
  type: NodePort
  nodePort: 32150

#postgresqlDataDir: /bitnami/postgresql

postgresqlDatabase: "postgres"
postgresqlUsername: "postgres"
```

And I am running into issues:

1. postgres user password is not initialized
1. When trying to connect to container in initialize the password manually, I receive the following error:
```
psql: local user with ID 1001 does not exist
```
1. When trying to connect with `psql -U postgres` and altering the password with `ALTER USER postgres WITH PASSWORD '####'`, still cannot connect to the server (authentication failed)
