### ISSUE TITLE
Environment variables not set when used in docker-compose

### ISSUE THREAD

**Issue by milosjovac** [timescale/timescaledb-docker#71]
Hi, 

I have a problem with setting timescale credentials when using it inside docker-compose file. It looks like environment variables are not read and docker image starts with the default values. Example `docker-compose.yml`:

```yml
version: "3.7"

services:
  timescale:
    image: timescale/timescaledb
    container_name: timescale
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - "POSTGRES_USER:postgres"
      - "POSTGRES_PASSWORD:postgres"
```

By executing `docker-compose up` It starts but in logs there is a following warning:

```
timescale    | ****************************************************
timescale    | WARNING: No password has been set for the database.
timescale    |          This will allow anyone with access to the
timescale    |          Postgres port to access your database. In
timescale    |          Docker's default configuration, this is
timescale    |          effectively any other container on the same
timescale    |          system.
timescale    | 
timescale    |          Use "-e POSTGRES_PASSWORD=password" to set
timescale    |          it in "docker run".
timescale    | ****************************************************
```

And when I try to access it:

```sh
> psql -U postgres -h localhost -p 5432
Password for user username: 
psql: FATAL:  password authentication failed for user "postgres"
```

In docker-compose logs it throws:

```
timescale    | FATAL:  password authentication failed for user "postgres"
timescale    | DETAIL:  User "postgres" has an empty password.
timescale    |  Connection matched pg_hba.conf line 95: "host all all all md5"
```
