### ISSUE TITLE
telemetry disabled by default

### ISSUE THREAD

**Issue by lssilva** [timescale/timescaledb-docker#82]
It would be nice to have telemetry to be disabled by default

**Comment by jflambert** [comment]
Yes please

**Comment by maltalex** [comment]
If anyone's looking for a quick way to disable it:

`docker run timescale/timescaledb:1.6.0-pg11 postgres  -c  'timescaledb.telemetry_level=off'`

or, if using compose:

```
db:
   image: timescale/timescaledb:1.6.0-pg11
   ...
   command: postgres -c  'timescaledb.telemetry_level=off'
```
